### PR TITLE
cmake .. goes to previous directory

### PR DESCRIPTION
**Pull request by thewhitetulip**
and the parent dir doesn't have a Cmake.txt file. This way we are able to build the app.

### CODE REVIEW

**Comment by voldyman** [comment]
ah, it should be `cd build` instead of cmake .

**Comment by thewhitetulip** [comment]
Okay, I was unable to do with cmake :D, I will try using cd build

**Comment by thewhitetulip** [comment]
Okay, I wasn't able to build the source.

`make: *** No targets specified and no makefile found.  Stop.`

**Comment by voldyman** [comment]
works perfectly

```
┌─[voldyman@ares:~/code]
└─> git clone git@github.com:voldyman/scribble.git
┌─[voldyman@ares:~/code]
└─> cd scribble/
l┌─[voldyman@ares:~/code/scribble on master]
└─> ls
cmake  CMakeLists.txt  data  README.md  screenshots  src
┌─[voldyman@ares:~/code/scribble on master]
└─> cd^C
┌─[voldyman@ares:~/code/scribble on master]
└─> mkdir build
┌─[voldyman@ares:~/code/scribble on master]
└─> cd build/
┌─[voldyman@ares:~/code/scribble/build on master]
└─> !cm
cmake .. && make
-- The C compiler identification is GNU 4.9.2
```

**Comment by thewhitetulip** [comment]
Yes, I was able to build it.

`[100%] Building C object CMakeFiles/scribble.dir/src/Widgets/NoteView.c.o
Linking C executable scribble
[100%] Built target scribble
thewhitetulip@thewhitetulip:~/code/scribble/build$ ./scribble 

*\* (scribble:6653): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-vIBIru33EJ: Connection refused

*\* (scribble:6653): ERROR **: NoteView.vala:28: Failed to import: Error opening file: No such file or directory
Trace/breakpoint trap (core dumped)
`

**Comment by voldyman** [comment]
that error is because i have hardcoded the css file location, you might want to fix that.

**Comment by thewhitetulip** [comment]
hardcoded where?

**Comment by voldyman** [comment]
https://github.com/voldyman/scribble/blob/master/src/Widgets/NoteView.vala#L23
can we have this conversation over IRC?

**Pull request closed without merging**
